# Generated by Django 3.0 on 2021-09-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getinvoicelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.IntegerField()),
                ('inv_date', models.DateField()),
                ('buy_name', models.CharField(max_length=50)),
                ('inv_net_amt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='invoice_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mfg', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('taxable_amount', models.CharField(max_length=50)),
                ('cgst', models.CharField(max_length=50)),
                ('sgst', models.CharField(max_length=50)),
                ('igst', models.CharField(max_length=50)),
                ('total_amount', models.CharField(max_length=50)),
            ],
        ),
    ]
