# Generated by Django 3.0 on 2021-09-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice_Product',
            new_name='Product',
        ),
    ]
