# Generated by Django 3.0 on 2021-09-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210906_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='product',
            table='invoice_product',
        ),
    ]
