# Generated by Django 3.0 on 2021-09-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20210906_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='igst',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
